name: Deploy to ECR

on:
  push:
    branches: [ fixes/listview ]

jobs:
  build:
    name: Build and Push Image to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        
        aws-access-key-id : ASIARHJJMYY465MJJKYK
        aws-secret-access-key: jbpHC6FxNYkmI8VB0rPg4HV5ghyV/XL7VDYbHCmU
        aws-session-token : IQoJb3JpZ2luX2VjEGgaCmV1LW5vcnRoLTEiSDBGAiEA25pfy4Nm45tR+IdmuHgEY9Q5yggJA5iFTkdy5awUE+ACIQDjTQuv3dkObTCe/FbvJg38plN4Us7ngD/a/+EzwnvSaSqAAwjR//////////8BEAAaDDA4NDM3NTU1MzU5MyIMl6iv/JCU1+Cfwh/YKtQCU1S/1ySWrTUdERSxkzcKGc+yJBmpcCuPVk2j845obwLXo3/qrzqh0qcMzzCXPt8BYPdWyFAo7QqHvFKc6N9iyN5EQ1Mc2cp+QBl/dck05byRnWxd5TSMwDC+mwX390l2Yn+0Dt1oLh+e3dqSlrOIr3fdm+eG15tmM4WzoioMAzV2qBW6giUMwf5GGPpLOYhgmODNU40mtJDiEKQmo8o2lUDfId05xgAlyesfH80VlVluhYQ2JZ6LUFEZcQyJ31eeJLN075oyiQ7/6LzGkwbhPwsLvpJ7FYGMyiP+1A280mSZe+3wH4Ha2ZS/ppq14T5SkIU/BoDCI5inRNemSwKHhmK9liQUzoT02vTPO9+H6n9eIEbkUjQOCsZd0SOtOWZroWAyNLXUDWRdWS9Sy6AY3uNjnVp6keF1K1fAx2186gu+O+dTvmnW7jnxcz7bYrXFlFhRSzDp+ee4BjqmAe6+1gQL3azLpDRqlbGkCx1MF7qwXr4zz8h0wXAzeM/EPJ2l3CD6fqf8Eq62ToLkA7R710b38+T7RbrosBX41XHpdMbJqgNny0i3D7MFxVdJVQe85JwRy/QsHBHC1PYeOE2RaOX8ymoInSj83Zj/QzNdJcsbMIn1Jby9nvRjQ2XJhWZqnFbROPErIKeHWouARl9z7/7a1Ke0z9GDI6J6YdmaWuz5wKA=
        aws-region: eu-north-1

    - name: Authenticate Docker to ECR
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 084375553593.dkr.ecr.eu-north-1.amazonaws.com

    - name: Build Docker image
      run: |
        docker build -t crm-frontend .

    - name: Tag Docker image
      run: |
        docker tag crm-frontend:latest 084375553593.dkr.ecr.eu-north-1.amazonaws.com/crm-frontend:latest

    - name: Push Docker image to ECR
      run: |
        docker push 084375553593.dkr.ecr.eu-north-1.amazonaws.com/crm-frontend:latest

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.TEST1 }}" > crm.pem
        chmod 600 crm.pem
        ssh -o StrictHostKeyChecking=no -i crm.pem ubuntu@ec2-13-51-212-186.eu-north-1.compute.amazonaws.com << 'EOF'
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 084375553593.dkr.ecr.eu-north-1.amazonaws.com
          
          docker stop crm-frontend || true
          docker rm crm-frontend || true
        
          docker run -d --name crm-frontend -p 3000:80 084375553593.dkr.ecr.eu-north-1.amazonaws.com/crm-frontend:latest
           
